# Generated by Django 4.0.3 on 2022-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gis_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('school', models.CharField(max_length=20)),
                ('checkdate', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('responsibilityman', models.CharField(max_length=20)),
                ('locate_x', models.CharField(max_length=20)),
                ('locate_y', models.CharField(max_length=20)),
            ],
        ),
    ]
