# Generated by Django 4.0.3 on 2022-04-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0002_gis_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gis_table',
            name='school',
        ),
    ]
