# Generated by Django 4.0.3 on 2022-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0003_remove_gis_table_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='gis_table',
            name='locate_x_float',
            field=models.FloatField(default=100.111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gis_table',
            name='locate_y_float',
            field=models.FloatField(default=79.999),
            preserve_default=False,
        ),
    ]
