# Generated by Django 4.0.3 on 2022-05-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0004_gis_table_locate_x_float_gis_table_locate_y_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='gis_table',
            name='address',
            field=models.CharField(default='addresstest', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gis_table',
            name='phone',
            field=models.CharField(default='1324455666', max_length=20),
            preserve_default=False,
        ),
    ]
