# Generated by Django 4.0.3 on 2022-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0005_gis_table_address_gis_table_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='positive_line_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_lng', models.FloatField()),
                ('center_lat', models.FloatField()),
                ('center_radius', models.FloatField()),
                ('line_points', models.CharField(max_length=500)),
            ],
        ),
    ]
