# Generated by Django 4.0.3 on 2022-10-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0006_positive_line_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='checkdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locate_x',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locate_y',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='responsibilityman',
        ),
        migrations.RemoveField(
            model_name='user',
            name='result',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.CharField(default='@blank.com', max_length=100),
            preserve_default=False,
        ),
    ]
