# Generated by Django 4.0.3 on 2022-10-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0007_remove_user_checkdate_remove_user_id_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='positive_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=20)),
                ('people_name', models.CharField(max_length=20)),
                ('people_id_card', models.FloatField()),
                ('time', models.CharField(max_length=20)),
                ('line_info', models.CharField(max_length=20)),
                ('locate_x_float', models.FloatField()),
                ('locate_y_float', models.FloatField()),
            ],
        ),
    ]
