# Generated by Django 4.0.3 on 2022-10-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0008_positive_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='positive_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=20)),
                ('people_name', models.CharField(max_length=20)),
                ('people_id_card', models.FloatField()),
                ('time', models.CharField(max_length=20)),
                ('line_info', models.CharField(max_length=20)),
            ],
        ),
    ]
