# Generated by Django 4.0.3 on 2022-10-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_welcome', '0009_positive_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='check_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=20)),
                ('point_name', models.CharField(max_length=20)),
                ('poind_address', models.CharField(max_length=100)),
                ('locate_x_float', models.FloatField()),
                ('locate_y_float', models.FloatField()),
            ],
        ),
    ]
